### ISSUE TITLE
Hello World does not compile

### ISSUE THREAD

**Issue by rm-rf-etc** [nodejs/node-addon-examples#115]
Node version: 10.15.1
MacOS version: 10.14.6

I followed the instructions in this hello-world example:
https://github.com/nodejs/node-addon-examples/tree/master/1_hello_world

These are my build errors:
```
$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.0
gyp info using node@10.15.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/hello/hello.o
../hello.cc:6:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../hello.cc:7:26: error: no member named 'New' in 'v8::String'
  NanReturnValue(String::New("world"));
                 ~~~~~~~~^
../hello.cc:11:16: error: use of undeclared identifier 'NanSymbol'
  exports->Set(NanSymbol("hello"), FunctionTemplate::New(Method)->GetFunction());
               ^
../hello.cc:11:58: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Nan::NAN_METHOD_RETURN_TYPE (Nan::NAN_METHOD_ARGS_TYPE)'
      (aka 'void (const FunctionCallbackInfo<v8::Value> &)')
  exports->Set(NanSymbol("hello"), FunctionTemplate::New(Method)->GetFunction());
                                                         ^~~~~~
/Users/rchristian/Library/Caches/node-gyp/10.15.1/include/node/v8.h:5645:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
4 errors generated.
make: *** [Release/obj.target/hello/hello.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rchristian/.config/yarn/global/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/rchristian/.nvm/versions/node/v10.15.1/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/rchristian/MyProjects/sandbox/hello_go2
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok
```

**Comment by mhdawson** [comment]
hmm, we should probably replace that example with a N-API or node-addon-api version since this repo is more actively maintained for those options.

@gengjiawen has done some work to fix the nan versions recently so maybe he can help with this specific issue.  The example in https://github.com/nodejs/node-addon-examples/tree/master/1_hello_world/nan  should work as I believe he has recently made sure that the examples all work and are tested on checkin.

**Comment by mhdawson** [comment]
The other option is removing the text in the example as we don't have the equivalent for the other examples...

**Comment by rm-rf-etc** [comment]
I was able to build the N-API example here https://github.com/nodejs/node-addon-examples/blob/master/1_hello_world/node-addon-api/hello.cc

I can't recall what is different from the readme tutorial.

Thank you for maintaining this project.

**Comment by mhdawson** [comment]
PR to remove stale doc: https://github.com/nodejs/node-addon-examples/pull/116
