### ISSUE TITLE
Hello World example doesn't build

### ISSUE THREAD

**Issue by arthurakay** [nodejs/node-addon-examples#25]
Trying to follow the hello world example, I get stopped at Step 5:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/hello/hello.o
../hello.cc:7:26: error: no member named 'New' in 'v8::String'
  NanReturnValue(String::New("world"));
                 ~~~~~~~~^
../node_modules/nan/nan.h:401:81: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                                                ^
../hello.cc:11:16: warning: 'NanSymbol' is deprecated [-Wdeprecated-declarations]
  exports->Set(NanSymbol("hello"), FunctionTemplate::New(Method)->GetFunction());
               ^
../node_modules/nan/nan.h:499:51: note: 'NanSymbol' has been explicitly marked deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../hello.cc:11:58: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'void
      (const v8::FunctionCallbackInfo<v8::Value> &)'
  exports->Set(NanSymbol("hello"), FunctionTemplate::New(Method)->GetFunction());
                                                         ^~~~~~
/Users/arthurakay/.node-gyp/0.12.0/deps/v8/include/v8.h:3456:16: note: passing argument to parameter
      'isolate' here
      Isolate* isolate,
               ^
1 warning and 2 errors generated.
make: *** [Release/obj.target/hello/hello.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/arthurakay/www/node_addons/quark
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

While I'm fairly experienced in Node.js, I'm an absolute noob in V8 and NAN. I would guess this is a Node version problem, but I was hoping someone might help clear things up for me. Thanks!

Mac OS X 10.10.2, other versions (node, etc) in the callstack above.

**Comment by arthurakay** [comment]
Err wait, I see the `nan` folder and can use that code. Sorry.

I simply expected the README to give me working code out of the box, perhaps that should be updated.

**Comment by rfcheng** [comment]
Hi arthurakay,
I also use Mac OS X 10.10.2 and got exactly the same callstack as yours. How did you fix the node-gyp build problem from the code in the nan folder? Thanks!

**Comment by arthurakay** [comment]
Running the code in the nan folder worked fine for me -- I had problems copy/pasting the code in the README for that example

**Comment by rfcheng** [comment]
It works! We should use the hello.cc from the nan folder at the same url (https://github.com/nodejs/node-addon-examples/tree/master/1_hello_world) where the direction for Example 1 is, not any other files from the nan folder of ./node_modules/nan/ under our  build directory. Thanks!
