### ISSUE TITLE
Error when running .js file using addon (node-addon-api)

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/node-addon-examples#98]
I built the Hello World addon using the node-addon-api successfully, but this is what happened when I tried to run it:
```
E:\programming\node-addon-api_example_helloworld>node hello.js
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'bindings'
Require stack:
- E:\programming\node-addon-api_example_helloworld\hello.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:681:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:16:16)[39m
    at Object.<anonymous> (E:\programming\node-addon-api_example_helloworld\hello.js:1:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:774:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:641:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'E:\\programming\\node-addon-api_example_helloworld\\hello.js'[39m ]
}
```
The module user code is:
```js
const addon = require("bindings")("hello");

console.log(addon.hello());
```
[I just hope the problem isn't the use of double-quotes instead of single-quotes.]

And I need a good place where I can go to learn about how to use the API and the C++ wrapper in more depth.

**Comment by kevinGodell** [comment]
Did you run `npm install bindings` to install the bindings module? That is used as a helper to find the path of the binary. Alternatively, you could just specify the path to the compiled addon file if you don't want to use the bindings module.

**Comment by mhdawson** [comment]
Pretty sure the issues is what @kevinGodell mentions.  I do that all the time and then it work after running the npm install.

**Comment by helio-frota** [comment]
Hi,

I think this issue can be closed, I saw the same error when I forgot to install `bindings` module.
